### PR TITLE
FilesColor.cna, updated exe's, and a few alias

### PR DESCRIPTION
**Pull request by Maleick**
- FilesColor.cna - https://github.com/mgeeky/cobalt-arsenal
- Added help information to sharpview_alias.cna
- Added watson_alias.cna 
- Added Get-ServiceAcl.ps1
- Added Get-LAPSPasswords.ps1
- Various updated exe's

### CODE REVIEW

**Comment by Maleick** [comment]
I noticed that spoolscript is missing some dependencies, going to go through and look at all the new changes and make some adjustments.

**Comment by josephkingstone** [comment]
Going to look through your changes today. Thanks for the help. Added you on Twitter, please send me a DM.

**Comment by Maleick** [comment]
I would like to contribute. Unable to locate you on Twitter; I am @infoMaleick.

**Comment by josephkingstone** [comment]
@n00brage - I followed you this morning.

**Pull request closed without merging**
